WT_ACCESS_TOKEN='ADD YOUR WEBEX TEAMS CHATBOT TOKEN'
WT_ROOM_ID='ADD YOUR WEBEX TEAMS ROOM ID'
MERAKI_API_KEY='ADD YOUR MERAKI DASHBOARD API KEY'
MERAKI_ORG_ID='ADD YOUR MERAKI ORG ID'
MERAKI_CAMS=['LIST THE CAMERA LOOKING AT YOUR MT20']
MERAKI_BASEURL='https://api.meraki.com/api/v1'